### ISSUE TITLE
ERROR: bob.extension.test_pkgconfig.test_cflags_other

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.extension#11]
```
======================================================================
ERROR: bob.extension.test_pkgconfig.test_cflags_other
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/bob/extension/test_pkgconfig.py", line 41, in test_cflags_other
    pkg = pkgconfig('gmodule-export-2.0')
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/bob/extension/pkgconfig.py", line 131, in __init__
    raise RuntimeError("pkg-config package `%s' was not found" % name)
RuntimeError: pkg-config package `gmodule-export-2.0' was not found
-------------------- >> begin captured logging << --------------------
root: DEBUG: Running `/opt/conda/envs/_test/bin/pkg-config --modversion gmodule-export-2.0'
--------------------- >> end captured logging << ---------------------
```
Full log: https://circleci.com/gh/conda-forge/bob.extension-feedstock/10
Pull: https://github.com/conda-forge/bob.extension-feedstock/pull/3
The test: https://github.com/bioidiap/bob.extension/blob/master/bob/extension/test_pkgconfig.py#L41

**Comment by siebenkopf** [comment]
I haven't written that test, but it seems that it tests for a package that isn't there. @anjos: Do you think it is safe to delete this test, or test for another package?

**Comment by anjos** [comment]
Should be safe. It is not the first time thought we have an issue with a package that is not installed. It seems to be tricky to find an installed package that is installed consistently everywhere. Out of curiosity does "pkg-config" provide a pkg-config package or a standard way to test it?

**Comment by 183amir** [comment]
In `conda-forge`, they install a package (`freetype`) and test against that one. Please look at here: `https://github.com/conda-forge/pkg-config-feedstock/blob/master/recipe/meta.yaml#L27`

**Comment by anjos** [comment]
Freetype should be OK, as that dep is required for matplotlib anyways. Probably better than the `gmodule` we're currently using. Please go ahead.

**Comment by anjos** [comment]
We'll need to change the travis scripts as well, of course.
