### ISSUE TITLE
Catching exceptions in debug mode makes it impossible to use gdb or gdb-python

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.extension#8]
When using the ``BOB_TRY`` and ``BOB_CATCH_...`` macros, any C++ exception in the C++ code (and in the binding code) is caught and reported as a python exception:
https://github.com/bioidiap/bob.extension/blob/master/bob/extension/include/bob.extension/defines.h#L36 
While this should be the desired practice in **release** mode (i.e., the python program is not stopped by the C++ exception), in **debug** mode this might be a bad idea, as debuggers like ``gdb`` (or more specifically, ``gdb-python``) do not stop at the place, where the exception happens.

So, do you think it is a good idea to **disable** the exception handling by ``BOB_TRY`` and ``BOB_CATCH_...`` in **debug** mode, i.e., when the ``BOB_DEBUG`` flag is set?

**Comment by anjos** [comment]
Sure. Seems like a good idea in debug mode. My only concern is that many people do set `debug=true` on their buildouts. Will that influence this?

**Comment by siebenkopf** [comment]
Hmm... I guess so. This highly depends on which packages they have compiled in debug mode. If they only compile their package and use a global installation of the other bob packages (which is in release mode), only their C/C++ code will be affected. When they compile whole bob in debug mode (which is a bad idea, IMHO), then all C++ exceptions will result in the C++ exception to be reported, and the python program will be killed.

Note that the packages on Travis are all compiled in release mode, so there is no change expected.

Hopefully, it would be enough to properly document that change.

**Comment by anjos** [comment]
Ok.

**Comment by siebenkopf** [comment]
I have just realized that the ``debug`` flag is also respected, when installing dependent packages as eggs. I am not sure if this is, what we want. I don't think that eggs should ever be compiled/installed in debug mode...
